name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Post Message to Webex Room
      uses: chrivand/action-webex-js@main
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
        MARKDOWN_MESSAGE: "**깃헙 액션 101 워크샵에서 보내는 메시ㅣ지입니다. 저는 최문석입니다. from ${{ github.repository }}.**"